db:
 images: klaemo/couchdb:2.0.0
 port:
 - "5984:5984"
 enviroment:
 - COUCHDB_USER=alex
 - COUCHDB_PASSWORD=123456
 app:
  image: ibmcom/swift-ubuntu
  ports:
  - "8080:8080"
  volumes:
  - .:/root/FoodTruckAPI
  command: bash -c "cd /root/FoodTruckAPI && swift build --clean && swift build --configuration release && ./.build/release/FoodTruckServer"
  links:
  - db:localhost

